# Generated by Django 5.0 on 2024-12-21 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='swap_skill_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_bookings', to='core.category'),
        ),
        migrations.AddField(
            model_name='booking',
            name='swap_skill_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='swap_skill_duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='swap_skill_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
